import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('screen');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'black',
    width,
    height,
  },
  passwordWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 201, 242, 0.25)',
    height: 48,
    paddingHorizontal: 16,
  },
  inputWrapper: { // New wrapper for email input with background
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.12)', // Light background for input
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 201, 242, 0.25)',
    height: 48,
    paddingHorizontal: 16,
  },
  backgroundAnimation: {
    position: 'absolute',
    width,
    height,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1,
    backgroundColor: '#0A0A6E',
  },
  keyboardAvoidView: {
    flex: 1,
    zIndex: 2,
    width: '100%',
    height: '100%',
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    paddingTop: 20,
  },
  formContainer: {
    width: width * 0.85,
    backgroundColor: 'rgba(10, 10, 40, 0.70)',
    borderRadius: 16,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
    borderWidth: 1,
    borderColor: 'rgba(167, 167, 255, 0.3)',
  },
  headerContainer: {
    alignItems: 'center',
    marginBottom: 30,
  },
  inputContainer: {
    marginBottom: 20,
  },
  label: {
    fontFamily: 'Lexend-Medium',
    fontSize: 14,
    color: '#F0F0FF',
    marginBottom: 8,
  },
  input: {
    flex: 1,
    color: '#FFFFFF',
    fontFamily: 'Lexend-Regular',
    fontSize: 16,
  },
  buttonContainer: {
    backgroundColor: 'rgba(42, 42, 204, 0.25)',
    borderRadius: 8,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 201, 242, 0.5)',
  },
  buttonText: {
    color: '#FFFFFF',
    fontFamily: 'Lexend-SemiBold',
    fontSize: 18,
    textShadowColor: '#FFD3F4',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  switchModeButton: {
    marginTop: 20,
    alignItems: 'center',
  },
  switchModeText: {
    color: '#FFD3F4',
    fontFamily: 'Lexend-Medium',
    fontSize: 14,
    textShadowColor: '#A7A7FF',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 5,
  },
  errorText: {
    color: '#FF6666',
    fontFamily: 'Lexend-Medium',
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 10,
    textShadowColor: '#FF0000',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 5,
  },
  successAnimationContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(10, 10, 60, 0.9)',
  },
  successAnimationWrapper: {
    width: width * 0.5,
    height: width * 0.5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  successAnimation: {
    width: '100%',
    height: '100%',
  },
});
