import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#282828',
  },
  headerContainer: {
    backgroundColor: 'rgb(43, 43, 43)',
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 10,
    paddingHorizontal: 16,
    paddingBottom: 10,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 3,
    borderBottomWidth: 1,
    borderBottomColor: 'rgb(255, 200, 0)',
  },
  backButton: {
    marginRight: 16,
  },
  headerTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontFamily: 'Lexend-SemiBold',
  },
  contentContainer: {
    paddingHorizontal: 20,
    paddingTop: 24,
  },
  sectionTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    fontFamily: 'Lexend-SemiBold',
    marginBottom: 16,
  },
  card: {
    backgroundColor: 'rgba(60, 60, 60, 0.7)',
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 201, 242, 0.15)',
  },
  fieldContainer: {
    marginBottom: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  fieldLabel: {
    color: '#AAAAAA',
    fontSize: 14,
    fontFamily: 'Lexend-Regular',
  },
  fieldValue: {
    color: '#FFFFFF',
    fontSize: 16,
    fontFamily: 'Lexend-Medium',
    flex: 1,
    textAlign: 'right',
  },
  fieldNameContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    flex: 1,
  },
  editButton: {
    marginRight: 8,
    padding: 4,
  },
  editNameContainer: {
    marginTop: 12,
  },
  saveButtonContainer: {
    backgroundColor: 'rgba(42, 42, 204, 0.25)',
    borderRadius: 8,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 201, 242, 0.5)',
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontFamily: 'Lexend-SemiBold',
    fontSize: 16,
    textShadowColor: '#FFD3F4',
    textShadowOffset: {width: 0, height: 0},
    textShadowRadius: 10,
  },
  editNameInput: {
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 8,
    height: 40,
    paddingHorizontal: 12,
    color: '#FFFFFF',
    fontFamily: 'Lexend-Regular',
    fontSize: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 201, 242, 0.25)',
  },
  animationProgressContainer: {
    marginTop: 20,
    marginBottom: 16,
    padding: 16,
    backgroundColor: 'rgba(60, 60, 60, 0.7)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 201, 242, 0.15)',
  },
  animationProgressTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    fontFamily: 'Lexend-SemiBold',
    marginBottom: 16,
  },
  levelRowContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    height: 50,
  },
  animationContainer: {
    width: 50,
    height: 50,
  },
  progressBarContainer: {
    flex: 1,
    height: 20,
    backgroundColor: '#444444',
    borderRadius: 10,
    marginHorizontal: 12,
    position: 'relative',
  },
  progressBarFill: {
    height: '100%',
    borderRadius: 10,
  },
  checkpointMarker: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#FFFFFF',
    position: 'absolute',
    top: '50%',
    marginTop: -4,
  },
  levelNameContainer: {
    minWidth: 100,
  },
  levelName: {
    color: '#FFFFFF',
    fontSize: 14,
    fontFamily: 'Lexend-Medium',
    textAlign: 'left',
  },
  connectorLine: {
    width: 2,
    backgroundColor: '#666666',
    position: 'absolute',
    left: 25, // Center of the fire animation
    top: 50, // Start from bottom of the fire animation
  },
});
