import { StyleSheet, Dimensions } from 'react-native';

const { height, width } = Dimensions.get('screen');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'black',
    width: width,
    height: height,
    // Add properties to ensure content goes to the very top of the screen
    paddingTop: 0,
    marginTop: 0,
  },
  backgroundAnimation: {
    position: 'absolute',
    width: width,
    height: height,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  textContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 2,
  },
  titleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  brainTextStyle: {
    fontSize: 50,
    fontFamily: 'Supercharge-JRgPo',
    color: '#FFEB74',
    textShadowColor: 'rgba(0, 0, 0, 1)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 10,
    letterSpacing: 2,
    textAlign: 'center',
    marginRight: -8,
  },
  buzzTextStyle: {
    fontSize: 50,
    fontFamily: 'Supercharge-JRgPo',
    color: '#FFFFFF',
    textShadowColor: 'rgba(0, 0, 0, 1)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 10,
    letterSpacing: 3,
    marginLeft: 8,
    textAlign: 'center',
  },
  lightningContainer: {
    width: width,
    height: height,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1,
  },
  lightningAnimation: {
    width: '100%',
    height: '100%',
  },
  enterButtonContainer: {
    position: 'absolute',
    bottom: '40%',
    alignSelf: 'center',
    zIndex: 3,
  },
  enterButton: {
    paddingVertical: 3,
    paddingHorizontal: 10,
    borderColor: 'white',
    borderRadius: 30,
    backgroundColor: 'transparent',
  },
  enterButtonText: {
    color: 'white',
    fontSize: 12,
    fontFamily: 'Lexend-Medium',
    letterSpacing: 3,
    textAlign: 'center',
  },
  cornerTL: {
    position: 'absolute',
    top: 2,
    left: 2,
    width: 6,
    height: 6,
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderColor: 'white',
  },
  cornerBR: {
    position: 'absolute',
    bottom: 2,
    right: 2,
    width: 6,
    height: 6,
    borderBottomWidth: 1,
    borderRightWidth: 1,
    borderColor: 'white',
  },
});
