import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: '100%',
    backgroundColor: '#1D1D1D',
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
    marginTop: 150,
  },
  bottomContainer: {
    padding: 20, // Adjust this to increase/decrease bottom spacing
    alignItems: 'center',
  },
  questionCount: {
    fontSize: 16,
    fontFamily: 'Lexend-Regular',
    color: '#FFFFFF',
    opacity: 0.8,
    marginBottom: 10,
    textAlign: 'center',
  },
  questionText: {
    fontSize: 22,
    fontFamily: 'Lexend-Bold',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 30,
    lineHeight: 30,
  },
  answersContainer: {
    width: '100%',
    maxWidth: 400,
    alignSelf: 'center',
    marginTop: 10,
  },
  answerButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 10,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  answerText: {
    fontSize: 16,
    fontFamily: 'Lexend-Medium',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  correctAnswer: {
    backgroundColor: 'rgba(76, 175, 80, 0.3)',
    borderColor: '#4CAF50',
    transform: [{ scale: 1.02 }],
    elevation: 6,
  },
  wrongAnswer: {
    backgroundColor: 'rgba(244, 67, 54, 0.3)',
    borderColor: '#F44336',
    transform: [{ scale: 1.02 }],
    elevation: 6,
  },
  progressBar: {
    width: '100%',
    height: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 3,
    marginTop: 10,
    marginBottom: 20,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: 'cyan',
    borderRadius: 3,
  },
  scoreContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  scoreText: {
    fontSize: 16,
    fontFamily: 'Lexend-SemiBold',
    color: '#FFFFFF',
    marginRight: 5,
  },
  scoreValue: {
    fontSize: 16,
    fontFamily: 'Lexend-Bold',
    color: '#FFFFFF',
  },
  endQuizButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F44336',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    },
    endQuizButtonText: {
    fontSize: 14,
    fontFamily: 'Lexend-Medium',
    color: '#FFFFFF',
    marginLeft: 5,
  },
  feedbackAnimationOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  errorText: {
    fontSize: 16,
    fontFamily: 'Lexend-Medium',
    color: '#FFFFFF',
    textAlign: 'center',
    opacity: 0.8,
    padding: 20,
  },
  });
