import {StyleSheet, Dimensions} from 'react-native';

const {height, width} = Dimensions.get('screen');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'black',
    width: width,
    height: height,
    paddingTop: 0,
    marginTop: 0,
  },
  backgroundAnimation: {
    position: 'absolute',
    width: width,
    height: height,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  textContainer: {
    overflow: 'visible',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 2,
    width: width,
    paddingHorizontal: 10,
  },
  titleContainer: {
    fontFamily: 'Supercharge-JRgPo',
    fontSize: 46,
    letterSpacing: 1,
    textAlign: 'center',
    overflow: 'visible',
  },
  lightningContainer: {
    width: width,
    height: height,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1,
  },
  lightningAnimation: {
    width: '100%',
    height: '100%',
  },
  enterButtonContainer: {
    position: 'absolute',
    bottom: '40%',
    alignSelf: 'center',
    zIndex: 3,
  },
  enterButton: {
    paddingVertical: 3,
    paddingHorizontal: 10,
    borderColor: 'white',
    borderRadius: 30,
    backgroundColor: 'transparent',
  },
  enterButtonText: {
    color: 'white',
    fontSize: 12,
    fontFamily: 'Lexend-Medium',
    letterSpacing: 3,
    textAlign: 'center',
  },
  cornerTL: {
    position: 'absolute',
    top: 2,
    left: 2,
    width: 6,
    height: 6,
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderColor: 'white',
  },
  cornerBR: {
    position: 'absolute',
    bottom: 2,
    right: 2,
    width: 6,
    height: 6,
    borderBottomWidth: 1,
    borderRightWidth: 1,
    borderColor: 'white',
  },
});
